/* ============================================================
   Tallo CPA – BIR Tax App
   atc-codes.js  –  EWT ATC Master List (BIR-official, 105 codes)
   ============================================================ */

const ATC_CODES = [
  // ── INDIVIDUAL (WI) ──────────────────────────────────────
  { atc:"WI010", desc:"Professional fees, <=3M",               longDesc:"PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M",                                                                                                                                                        rate:5.0,  payeeType:"Individual" },
  { atc:"WI011", desc:"Professional fees, >3M/VAT",            longDesc:"PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT",                                                                                                                                        rate:10.0, payeeType:"Individual" },
  { atc:"WI020", desc:"Prof. entertainers, <=3M",              longDesc:"PROFESSIONAL ENTERTAINERS (ACTORS, SINGERS, EMCEES, ETC.) - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                     rate:5.0,  payeeType:"Individual" },
  { atc:"WI021", desc:"Prof. entertainers, >3M/VAT",           longDesc:"PROFESSIONAL ENTERTAINERS - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                                        rate:10.0, payeeType:"Individual" },
  { atc:"WI030", desc:"Prof. athletes, <=3M",                  longDesc:"PROFESSIONAL ATHLETES (BASKETBALL PLAYERS, PELOTARIS, JOCKEYS) - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                rate:5.0,  payeeType:"Individual" },
  { atc:"WI031", desc:"Prof. athletes, >3M/VAT",               longDesc:"PROFESSIONAL ATHLETES - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                                            rate:10.0, payeeType:"Individual" },
  { atc:"WI040", desc:"Directors/producers, <=3M",             longDesc:"ALL DIRECTORS AND PRODUCERS (MOVIES, STAGE, RADIO, TV, MUSICAL) - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                               rate:5.0,  payeeType:"Individual" },
  { atc:"WI041", desc:"Directors/producers, >3M/VAT",          longDesc:"ALL DIRECTORS AND PRODUCERS - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                                      rate:10.0, payeeType:"Individual" },
  { atc:"WI050", desc:"Mgt/tech consultants, <=3M",            longDesc:"MANAGEMENT AND TECHNICAL CONSULTANTS - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                                          rate:5.0,  payeeType:"Individual" },
  { atc:"WI051", desc:"Mgt/tech consultants, >3M/VAT",         longDesc:"MANAGEMENT AND TECHNICAL CONSULTANTS - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                             rate:10.0, payeeType:"Individual" },
  { atc:"WI060", desc:"Bookkeeping agents, <=3M",              longDesc:"BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                                  rate:5.0,  payeeType:"Individual" },
  { atc:"WI061", desc:"Bookkeeping agents, >3M/VAT",           longDesc:"BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                     rate:10.0, payeeType:"Individual" },
  { atc:"WI070", desc:"Insurance agents, <=3M",                longDesc:"INSURANCE AGENTS AND INSURANCE ADJUSTERS - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                                      rate:5.0,  payeeType:"Individual" },
  { atc:"WI071", desc:"Insurance agents, >3M/VAT",             longDesc:"INSURANCE AGENTS AND INSURANCE ADJUSTERS - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                         rate:10.0, payeeType:"Individual" },
  { atc:"WI080", desc:"Talent fees - other, <=3M",             longDesc:"OTHER RECIPIENTS OF TALENT FEES - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                                               rate:5.0,  payeeType:"Individual" },
  { atc:"WI081", desc:"Talent fees - other, >3M/VAT",          longDesc:"OTHER RECIPIENTS OF TALENT FEES - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                                  rate:10.0, payeeType:"Individual" },
  { atc:"WI090", desc:"Non-employee directors, <=3M",          longDesc:"FEES OF DIRECTORS WHO ARE NOT EMPLOYEES - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                                                       rate:5.0,  payeeType:"Individual" },
  { atc:"WI091", desc:"Non-employee directors, >3M/VAT",       longDesc:"FEES OF DIRECTORS WHO ARE NOT EMPLOYEES - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                          rate:10.0, payeeType:"Individual" },
  { atc:"WI100", desc:"Rentals - property/personal",           longDesc:"RENTALS ON REAL/PERSONAL PROPERTY IN EXCESS OF P10,000 ANNUALLY; POLES, SATELLITES, TRANSMISSION FACILITIES, BILLBOARDS",                                                                                                                                          rate:5.0,  payeeType:"Individual" },
  { atc:"WI110", desc:"Cinematographic film rentals",          longDesc:"CINEMATOGRAPHIC FILM RENTALS AND OTHER PAYMENTS TO RESIDENT INDIVIDUAL FILM OWNERS, LESSORS OR DISTRIBUTORS",                                                                                                                                                       rate:5.0,  payeeType:"Individual" },
  { atc:"WI120", desc:"Contractors",                           longDesc:"INCOME PAYMENTS TO CERTAIN CONTRACTORS",                                                                                                                                                                                                                             rate:2.0,  payeeType:"Individual" },
  { atc:"WI130", desc:"Estate/trust distributions",            longDesc:"INCOME DISTRIBUTION TO THE BENEFICIARIES OF ESTATES AND TRUSTS",                                                                                                                                                                                                    rate:15.0, payeeType:"Individual" },
  { atc:"WI139", desc:"Brokers/RESPs, <=3M",                   longDesc:"GROSS COMMISSIONS OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS; FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS - GROSS INCOME DID NOT EXCEED P 3M",                                                        rate:5.0,  payeeType:"Individual" },
  { atc:"WI140", desc:"Brokers/RESPs, >3M/VAT",                longDesc:"GROSS COMMISSIONS OF BROKERS AND RESPs - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                                                           rate:10.0, payeeType:"Individual" },
  { atc:"WI150", desc:"Medical practitioners, >3M/VAT",        longDesc:"PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS BY HOSPITALS & CLINICS OR HMOs - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                                   rate:10.0, payeeType:"Individual" },
  { atc:"WI151", desc:"Medical practitioners, <=3M",           longDesc:"PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS BY HOSPITALS & CLINICS OR HMOs - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                                rate:5.0,  payeeType:"Individual" },
  { atc:"WI152", desc:"GPP partners, <=720K",                  longDesc:"PAYMENT BY GENERAL PROFESSIONAL PARTNERSHIPS (GPPs) TO ITS PARTNERS - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                      rate:10.0, payeeType:"Individual" },
  { atc:"WI153", desc:"GPP partners, >720K",                   longDesc:"PAYMENT BY GENERAL PROFESSIONAL PARTNERSHIPS (GPPs) TO ITS PARTNERS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                             rate:15.0, payeeType:"Individual" },
  { atc:"WI156", desc:"Credit card company payments",          longDesc:"INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES",                                                                                                                                                                                                                     rate:0.5,  payeeType:"Individual" },
  { atc:"WI157", desc:"Govt/GOCC supplier - services",         longDesc:"INCOME PAYMENTS BY GOVERNMENT AND GOCCs TO LOCAL/RESIDENT SUPPLIERS OF SERVICES",                                                                                                                                                                                   rate:2.0,  payeeType:"Individual" },
  { atc:"WI158", desc:"Top WA supplier - goods",               longDesc:"INCOME PAYMENT BY TOP WITHHOLDING AGENTS TO LOCAL/RESIDENT SUPPLIER OF GOODS",                                                                                                                                                                                      rate:1.0,  payeeType:"Individual" },
  { atc:"WI159", desc:"Govt personnel overtime",               longDesc:"ADDITIONAL INCOME PAYMENTS TO GOVERNMENT PERSONNEL FROM IMPORTERS, SHIPPING AND AIRLINE COMPANIES FOR OVERTIME SERVICES",                                                                                                                                           rate:15.0, payeeType:"Individual" },
  { atc:"WI160", desc:"Top WA supplier - services",            longDesc:"INCOME PAYMENT BY TOP WITHHOLDING AGENTS TO LOCAL/RESIDENT SUPPLIER OF SERVICES",                                                                                                                                                                                   rate:2.0,  payeeType:"Individual" },
  { atc:"WI515", desc:"Sales reps/MLM, <=3M",                  longDesc:"COMMISSIONS, REBATES, DISCOUNTS TO INDEPENDENT SALES REPRESENTATIVES AND MARKETING AGENTS - GROSS INCOME DID NOT EXCEED P 3M",                                                                                                                                     rate:5.0,  payeeType:"Individual" },
  { atc:"WI516", desc:"Sales reps/MLM, >3M/VAT",               longDesc:"COMMISSIONS, REBATES, DISCOUNTS TO INDEPENDENT SALES REPRESENTATIVES AND MARKETING AGENTS - GROSS INCOME MORE THAN P 3M OR VAT REGISTERED",                                                                                                                        rate:10.0, payeeType:"Individual" },
  { atc:"WI530", desc:"Embalmers by funeral parlors",          longDesc:"GROSS PAYMENTS TO EMBALMERS BY FUNERAL PARLORS",                                                                                                                                                                                                                     rate:1.0,  payeeType:"Individual" },
  { atc:"WI535", desc:"Pre-need co. to funeral parlors",       longDesc:"PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS",                                                                                                                                                                                                            rate:1.0,  payeeType:"Individual" },
  { atc:"WI540", desc:"Tolling fees - refineries",             longDesc:"TOLLING FEES PAID TO REFINERIES",                                                                                                                                                                                                                                   rate:5.0,  payeeType:"Individual" },
  { atc:"WI610", desc:"Agri products supplier, >300K",         longDesc:"INCOME PAYMENTS TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE P 300,000 WITHIN THE SAME TAXABLE YEAR",                                                                                                                                             rate:1.0,  payeeType:"Individual" },
  { atc:"WI630", desc:"Minerals/quarry (non-BSP)",             longDesc:"INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES (NON-BSP)",                                                                                                                                                                        rate:5.0,  payeeType:"Individual" },
  { atc:"WI632", desc:"Minerals/quarry (BSP)",                 longDesc:"INCOME PAYMENTS ON PURCHASES OF MINERALS BY BANGKO SENTRAL NG PILIPINAS FROM GOLD MINERS/SUPPLIERS",                                                                                                                                                               rate:1.0,  payeeType:"Individual" },
  { atc:"WI640", desc:"Govt/GOCC supplier - goods",            longDesc:"INCOME PAYMENTS BY GOVERNMENT AND GOCCs TO LOCAL/RESIDENT SUPPLIERS OF GOODS",                                                                                                                                                                                      rate:1.0,  payeeType:"Individual" },
  { atc:"WI650", desc:"MERALCO refund - active",               longDesc:"GROSS AMOUNT OF REFUND BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS",                                                                                                                                                                                              rate:15.0, payeeType:"Individual" },
  { atc:"WI651", desc:"MERALCO refund - terminated",           longDesc:"GROSS AMOUNT OF REFUND BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS",                                                                                                                                                                                          rate:15.0, payeeType:"Individual" },
  { atc:"WI660", desc:"Meter deposit int. - MERALCO res.",     longDesc:"INTEREST ON REFUND OF METER DEPOSIT - MERALCO RESIDENTIAL (>200 KWH)",                                                                                                                                                                                             rate:10.0, payeeType:"Individual" },
  { atc:"WI661", desc:"Meter deposit int. - MERALCO non-res.", longDesc:"INTEREST ON REFUND OF METER DEPOSIT - MERALCO NON-RESIDENTIAL (>200 KWH)",                                                                                                                                                                                         rate:10.0, payeeType:"Individual" },
  { atc:"WI662", desc:"Meter deposit int. - other DU res.",    longDesc:"INTEREST ON REFUND OF METER DEPOSIT - OTHER DISTRIBUTION UTILITIES RESIDENTIAL",                                                                                                                                                                                   rate:10.0, payeeType:"Individual" },
  { atc:"WI663", desc:"Meter deposit int. - other DU non-res.",longDesc:"INTEREST ON REFUND OF METER DEPOSIT - OTHER DISTRIBUTION UTILITIES NON-RESIDENTIAL",                                                                                                                                                                               rate:15.0, payeeType:"Individual" },
  { atc:"WI680", desc:"Political/campaign payments",           longDesc:"INCOME PAYMENTS BY POLITICAL PARTIES AND CANDIDATES FOR CAMPAIGN-RELATED GOODS AND SERVICES",                                                                                                                                                                       rate:5.0,  payeeType:"Individual" },
  { atc:"WI710", desc:"Interest - other debt instruments",     longDesc:"INTEREST INCOME FROM OTHER DEBT INSTRUMENTS NOT WITHIN COVERAGE OF DEPOSIT SUBSTITUTES AND RR 14-2012",                                                                                                                                                            rate:15.0, payeeType:"Individual" },
  { atc:"WI720", desc:"Locally produced raw sugar",            longDesc:"INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR",                                                                                                                                                                                                                     rate:1.0,  payeeType:"Individual" },
  { atc:"WI770", desc:"Joint venture supplier - goods",        longDesc:"INCOME PAYMENTS BY JOINT VENTURES TO LOCAL/RESIDENT SUPPLIER OF GOODS - INDIVIDUAL",                                                                                                                                                                               rate:1.0,  payeeType:"Individual" },
  { atc:"WI780", desc:"Joint venture supplier - services",     longDesc:"INCOME PAYMENTS BY JOINT VENTURES TO LOCAL/RESIDENT SUPPLIER OF SERVICES - INDIVIDUAL",                                                                                                                                                                            rate:2.0,  payeeType:"Individual" },
  { atc:"WI820", desc:"E-marketplace remittances",             longDesc:"GROSS REMITTANCES BY E-MARKETPLACE OPERATORS TO SELLERS/MERCHANTS - INDIVIDUAL",                                                                                                                                                                                   rate:0.5,  payeeType:"Individual" },
  { atc:"WI830", desc:"Digital financial svc remittances",     longDesc:"GROSS REMITTANCES BY DIGITAL FINANCIAL SERVICES PROVIDERS TO SELLERS/MERCHANTS - INDIVIDUAL",                                                                                                                                                                      rate:0.5,  payeeType:"Individual" },

  // ── NON-INDIVIDUAL / CORPORATE (WC) ──────────────────────
  { atc:"WC010", desc:"Professional fees, <=720K",             longDesc:"PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                            rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC011", desc:"Professional fees, >720K",              longDesc:"PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                   rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC020", desc:"Prof. entertainers, <=720K",            longDesc:"PROFESSIONAL ENTERTAINERS - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                                rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC021", desc:"Prof. entertainers, >720K",             longDesc:"PROFESSIONAL ENTERTAINERS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                                       rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC030", desc:"Prof. athletes, <=720K",                longDesc:"PROFESSIONAL ATHLETES - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                                    rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC031", desc:"Prof. athletes, >720K",                 longDesc:"PROFESSIONAL ATHLETES - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                                           rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC040", desc:"Directors/producers, <=720K",           longDesc:"ALL DIRECTORS AND PRODUCERS (MOVIES, STAGE, RADIO, TV, MUSICAL) - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                          rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC041", desc:"Directors/producers, >720K",            longDesc:"ALL DIRECTORS AND PRODUCERS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                                     rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC050", desc:"Mgt/tech consultants, <=720K",          longDesc:"MANAGEMENT AND TECHNICAL CONSULTANTS - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                     rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC051", desc:"Mgt/tech consultants, >720K",           longDesc:"MANAGEMENT AND TECHNICAL CONSULTANTS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                            rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC060", desc:"Bookkeeping agents, <=720K",            longDesc:"BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                             rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC061", desc:"Bookkeeping agents, >720K",             longDesc:"BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                    rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC070", desc:"Insurance agents, <=720K",              longDesc:"INSURANCE AGENTS AND INSURANCE ADJUSTERS - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                 rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC071", desc:"Insurance agents, >720K",               longDesc:"INSURANCE AGENTS AND INSURANCE ADJUSTERS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                        rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC080", desc:"Talent fees - other, <=720K",           longDesc:"OTHER RECIPIENTS OF TALENT FEES - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                          rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC081", desc:"Talent fees - other, >720K",            longDesc:"OTHER RECIPIENTS OF TALENT FEES - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                                 rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC100", desc:"Rentals - property/personal",           longDesc:"RENTALS ON REAL/PERSONAL PROPERTY IN EXCESS OF P10,000 ANNUALLY (CORPORATE)",                                                                                                                                                                                      rate:5.0,  payeeType:"Non-Individual" },
  { atc:"WC110", desc:"Cinematographic film rentals",          longDesc:"CINEMATOGRAPHIC FILM RENTALS - CORPORATE",                                                                                                                                                                                                                          rate:5.0,  payeeType:"Non-Individual" },
  { atc:"WC120", desc:"Contractors",                           longDesc:"INCOME PAYMENTS TO CERTAIN CONTRACTORS - CORPORATE",                                                                                                                                                                                                                rate:2.0,  payeeType:"Non-Individual" },
  { atc:"WC139", desc:"Brokers/RESPs, <=720K",                 longDesc:"GROSS COMMISSIONS OF BROKERS AND RESPs - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                                                   rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC140", desc:"Brokers/RESPs, >720K",                  longDesc:"GROSS COMMISSIONS OF BROKERS AND RESPs - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                                                          rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC150", desc:"Medical practitioners, >720K",          longDesc:"PROFESSIONAL FEES TO MEDICAL PRACTITIONERS BY HOSPITALS/CLINICS OR HMOs - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                         rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC151", desc:"Medical practitioners, <=720K",         longDesc:"PROFESSIONAL FEES TO MEDICAL PRACTITIONERS BY HOSPITALS/CLINICS OR HMOs - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                  rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC156", desc:"Credit card company payments",          longDesc:"INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES - CORPORATE",                                                                                                                                                                                                         rate:0.5,  payeeType:"Non-Individual" },
  { atc:"WC157", desc:"Govt/GOCC supplier - services",         longDesc:"INCOME PAYMENTS BY GOVERNMENT AND GOCCs TO LOCAL/RESIDENT SUPPLIERS OF SERVICES - CORPORATE",                                                                                                                                                                       rate:2.0,  payeeType:"Non-Individual" },
  { atc:"WC158", desc:"Top WA supplier - goods",               longDesc:"INCOME PAYMENT BY TOP WITHHOLDING AGENTS TO LOCAL/RESIDENT SUPPLIER OF GOODS - CORPORATE",                                                                                                                                                                          rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC160", desc:"Top WA supplier - services",            longDesc:"INCOME PAYMENT BY TOP WITHHOLDING AGENTS TO LOCAL/RESIDENT SUPPLIER OF SERVICES - CORPORATE",                                                                                                                                                                       rate:2.0,  payeeType:"Non-Individual" },
  { atc:"WC515", desc:"Sales reps/MLM, <=720K",                longDesc:"COMMISSIONS TO INDEPENDENT SALES REPRESENTATIVES AND MARKETING AGENTS - GROSS INCOME DID NOT EXCEED P 720,000",                                                                                                                                                    rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC516", desc:"Sales reps/MLM, >720K",                 longDesc:"COMMISSIONS TO INDEPENDENT SALES REPRESENTATIVES AND MARKETING AGENTS - GROSS INCOME EXCEEDS P 720,000",                                                                                                                                                           rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC535", desc:"Pre-need co. to funeral parlors",       longDesc:"PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS - CORPORATE",                                                                                                                                                                                               rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC540", desc:"Tolling fees - refineries",             longDesc:"TOLLING FEES PAID TO REFINERIES - CORPORATE",                                                                                                                                                                                                                       rate:5.0,  payeeType:"Non-Individual" },
  { atc:"WC610", desc:"Agri products supplier, >300K",         longDesc:"INCOME PAYMENTS TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE P 300,000 - CORPORATE",                                                                                                                                                              rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC630", desc:"Minerals/quarry (non-BSP)",             longDesc:"INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES (NON-BSP) - CORPORATE",                                                                                                                                                            rate:5.0,  payeeType:"Non-Individual" },
  { atc:"WC632", desc:"Minerals/quarry (BSP)",                 longDesc:"INCOME PAYMENTS ON PURCHASES OF MINERALS BY BSP - CORPORATE",                                                                                                                                                                                                      rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC640", desc:"Govt/GOCC supplier - goods",            longDesc:"INCOME PAYMENTS BY GOVERNMENT AND GOCCs TO LOCAL/RESIDENT SUPPLIERS OF GOODS - CORPORATE",                                                                                                                                                                          rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC650", desc:"MERALCO refund - active",               longDesc:"GROSS AMOUNT OF REFUND BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS - CORPORATE",                                                                                                                                                                                 rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC651", desc:"MERALCO refund - terminated",           longDesc:"GROSS AMOUNT OF REFUND BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS - CORPORATE",                                                                                                                                                                             rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC660", desc:"Meter deposit int. - MERALCO res.",     longDesc:"INTEREST ON REFUND OF METER DEPOSIT - MERALCO RESIDENTIAL - CORPORATE",                                                                                                                                                                                            rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC661", desc:"Meter deposit int. - MERALCO non-res.", longDesc:"INTEREST ON REFUND OF METER DEPOSIT - MERALCO NON-RESIDENTIAL - CORPORATE",                                                                                                                                                                                        rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC662", desc:"Meter deposit int. - other DU res.",    longDesc:"INTEREST ON REFUND OF METER DEPOSIT - OTHER DU RESIDENTIAL - CORPORATE",                                                                                                                                                                                           rate:10.0, payeeType:"Non-Individual" },
  { atc:"WC663", desc:"Meter deposit int. - other DU non-res.",longDesc:"INTEREST ON REFUND OF METER DEPOSIT - OTHER DU NON-RESIDENTIAL - CORPORATE",                                                                                                                                                                                       rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC680", desc:"Political/campaign payments",           longDesc:"INCOME PAYMENTS BY POLITICAL PARTIES AND CANDIDATES FOR CAMPAIGN-RELATED GOODS AND SERVICES - CORPORATE",                                                                                                                                                           rate:5.0,  payeeType:"Non-Individual" },
  { atc:"WC690", desc:"REIT income payments",                  longDesc:"INCOME PAYMENTS RECEIVED BY REAL ESTATE INVESTMENT TRUST (REIT)",                                                                                                                                                                                                   rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC710", desc:"Interest - other debt instruments",     longDesc:"INTEREST INCOME FROM OTHER DEBT INSTRUMENTS NOT WITHIN COVERAGE OF DEPOSIT SUBSTITUTES - CORPORATE",                                                                                                                                                               rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC720", desc:"Locally produced raw sugar",            longDesc:"INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR - CORPORATE",                                                                                                                                                                                                         rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC770", desc:"Joint venture supplier - goods",        longDesc:"INCOME PAYMENTS BY JOINT VENTURES TO LOCAL/RESIDENT SUPPLIER OF GOODS - CORPORATE",                                                                                                                                                                                rate:1.0,  payeeType:"Non-Individual" },
  { atc:"WC780", desc:"Joint venture supplier - services",     longDesc:"INCOME PAYMENTS BY JOINT VENTURES TO LOCAL/RESIDENT SUPPLIER OF SERVICES - CORPORATE",                                                                                                                                                                             rate:2.0,  payeeType:"Non-Individual" },
  { atc:"WC790", desc:"JV/consortium net income share",        longDesc:"SHARE OF CO-VENTURER/MEMBER FROM NET INCOME OF JOINT VENTURE/CONSORTIUM - CORPORATE",                                                                                                                                                                              rate:15.0, payeeType:"Non-Individual" },
  { atc:"WC820", desc:"E-marketplace remittances",             longDesc:"GROSS REMITTANCES BY E-MARKETPLACE OPERATORS TO SELLERS/MERCHANTS - CORPORATE",                                                                                                                                                                                    rate:0.5,  payeeType:"Non-Individual" },
  { atc:"WC830", desc:"Digital financial svc remittances",     longDesc:"GROSS REMITTANCES BY DIGITAL FINANCIAL SERVICES PROVIDERS TO SELLERS/MERCHANTS - CORPORATE",                                                                                                                                                                       rate:0.5,  payeeType:"Non-Individual" },
];

// Helper: get ATC by code
function getAtc(code) {
  return ATC_CODES.find(a => a.atc === code) || null;
}

// Helper: get ATCs for a payee type
function getAtcsByType(payeeType) {
  return ATC_CODES.filter(a => a.payeeType === payeeType);
}

// Helper: render an <option> list of ATCs
function renderAtcOptions(selected = '') {
  const groups = {
    'Individual (WI)':     ATC_CODES.filter(a => a.payeeType === 'Individual'),
    'Non-Individual (WC)': ATC_CODES.filter(a => a.payeeType === 'Non-Individual'),
  };
  let html = '<option value="">— Select ATC —</option>';
  for (const [label, items] of Object.entries(groups)) {
    html += `<optgroup label="${label}">`;
    for (const a of items) {
      const sel = a.atc === selected ? ' selected' : '';
      html += `<option value="${a.atc}"${sel}>${a.atc} — ${a.rate}% ${a.desc}</option>`;
    }
    html += '</optgroup>';
  }
  return html;
}
